# Generated by Django 3.0.8 on 2020-08-11 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safety_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Brand_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safety_app.Brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Category_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safety_app.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Discount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
