# Generated by Django 3.0.8 on 2020-08-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_app', '0002_auto_20200811_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Size',
            field=models.CharField(choices=[('F', 'Free'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('U', 'unknow')], max_length=80),
        ),
    ]
