# Generated by Django 3.0.8 on 2020-08-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_app', '0003_auto_20200811_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Brand_Name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Category_Name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Colour',
            new_name='colour',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Create_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Discount',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Discription',
            new_name='discription',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Expiry_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Modify_date',
            new_name='modify_date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Weight',
            new_name='weight',
        ),
    ]
