# Generated by Django 3.0.8 on 2020-08-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_app', '0004_auto_20200811_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='brand',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='category_name',
        ),
    ]
