# Generated by Django 3.0.8 on 2020-08-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_app', '0005_auto_20200811_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('F', 'Free'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('U', 'unknown')], max_length=80),
        ),
    ]
