# Generated by Django 3.0.8 on 2020-08-07 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0042_auto_20200806_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer_oder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(auto_now_add=True, max_length=32)),
                ('ac_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='NewspaperAPI.Consumer')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewspaperAPI.Consumer')),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewspaperAPI.Newspaper')),
            ],
        ),
    ]
