# Generated by Django 3.0.8 on 2020-08-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0044_auto_20200807_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='ac_no',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='consumer_order',
            name='ac_no',
            field=models.ManyToManyField(related_name='Consumer_ac_no', to='NewspaperAPI.Consumer'),
        ),
    ]
