# Generated by Django 3.0.8 on 2020-08-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0045_auto_20200807_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='ac_no',
        ),
        migrations.RemoveField(
            model_name='consumer_order',
            name='ac_no',
        ),
        migrations.AddField(
            model_name='consumer_order',
            name='ac_no',
            field=models.IntegerField(default=0),
        ),
    ]
