# Generated by Django 3.0.8 on 2020-08-08 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0046_auto_20200807_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer_order',
            name='newspaper',
        ),
        migrations.AddField(
            model_name='consumer_order',
            name='newspaper',
            field=models.ManyToManyField(related_name='Consumer_ac_no', to='NewspaperAPI.Newspaper'),
        ),
        migrations.CreateModel(
            name='Daily_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, max_length=32)),
                ('ac_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NewspaperAPI.Consumer_order')),
            ],
        ),
    ]
